/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#10131a",
        "on-surface": "#e1e2ec",
        "on-secondary-fixed-variant": "#004e5c",
        "on-primary-fixed-variant": "#5516be",
        "tertiary-container": "#ca8100",
        "inverse-surface": "#e1e2ec",
        "primary-fixed-dim": "#d0bcff",
        "primary-container": "#a078ff",
        "surface-dim": "#10131a",
        "on-secondary-container": "#00424e",
        "surface-bright": "#363941",
        "secondary-fixed": "#acedff",
        "primary": "#d0bcff",
        "on-background": "#e1e2ec",
        "on-secondary": "#003640",
        "secondary": "#4cd7f6",
        "surface": "#10131a",
        "on-primary-container": "#340080",
        "surface-tint": "#d0bcff",
        "surface-variant": "#32353d",
        "surface-container-low": "#191b23",
        "surface-container": "#1d1f27",
        "inverse-on-surface": "#2d3038",
        "on-surface-variant": "#cbc3d7",
        "error": "#ffb4ab",
        "secondary-container": "#03b5d3",
        "on-error": "#690005",
        "error-container": "#93000a",
        "primary-fixed": "#e9ddff",
        "outline": "#958ea0",
        "inverse-primary": "#6d3bd7",
        "tertiary-fixed-dim": "#ffb95f",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#2a1700",
        "on-primary": "#3c0091",
        "on-tertiary-container": "#3e2400",
        "on-primary-fixed": "#23005c",
        "on-secondary-fixed": "#001f26",
        "tertiary": "#ffb95f",
        "on-tertiary": "#472a00",
        "surface-container-high": "#272a32",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-highest": "#32353d",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary-fixed": "#ffddb8",
        "surface-container-lowest": "#0b0e15",
        "outline-variant": "#494454",
        "telegram": "#229ED9"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-3xs": "0.125rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
        "panel-padding-sm": "1rem",
        "panel-padding-lg": "1.5rem",
      },
      fontFamily: {
        "headline-xl-mobile": ["'Space Grotesk'", "sans-serif"],
        "display-hero": ["'Space Grotesk'", "sans-serif"],
        "headline-sm": ["'Space Grotesk'", "sans-serif"],
        "stat-counter": ["'Space Grotesk'", "sans-serif"],
        "body-sm": ["'Inter'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"],
        "label-caps": ["'Space Grotesk'", "sans-serif"],
        "display-hero-mobile": ["'Space Grotesk'", "sans-serif"],
        "headline-md": ["'Space Grotesk'", "sans-serif"],
        "title-md": ["'Inter'", "sans-serif"],
        "headline-xl": ["'Space Grotesk'", "sans-serif"],
        "headline-lg": ["'Space Grotesk'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "headline-lg-mobile": ["'Space Grotesk'", "sans-serif"]
      },
      fontSize: {
        "headline-xl-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-hero": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "600" }],
        "stat-counter": ["28px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "display-hero-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }],
        "title-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
